packages:
  - "."
minimumReleaseAge: 4320
blockExoticSubdeps: true
trustPolicy: no-downgrade
overrides:
  semver: 7.8.5
  chokidar: 4.0.1
  vite: 6.4.3
allowBuilds:
  '@swc/core': true
  esbuild: true
